spring:
  application:
    name: OnePay
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

frontend:
  url: ${FRONTEND_URL}

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: ${ACCESS_EXPIRATION}
    refresh-expiration-ms: ${REFRESH_EXPIRATION}



